
services:
  # чтобы пересобрать
  # docker-compose build --no-cache backend
  backend:
    hostname: backend
    build:
      context: ./fast_api_app
      dockerfile: Dockerfile
    command: poetry run python main.py
    volumes:
      - ./fast_api_app/:/usr/src/fast_api_app/
    ports:
      - "${OUT_BACK_PORT}:${IN_BACK_PORT}"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    hostname: postgres
    image: postgres:13.0-alpine
    ports:
      - "${OUT_DB_PORT}:${IN_DB_PORT}"
    env_file:
      - ./.env.dev


  frontend:
    build:
      context: ./vue_app/2048_front
      dockerfile: Dockerfile
    volumes:
      - ./vue_app/2048_front/:/usr/src/app/
    ports:
      - "8080:8080"
    depends_on:
      - backend